### ISSUE TITLE
[meta] Upgrade Ubuntu to Xenial

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-docs#119]
Ubuntu Xenial switched to systemd from upstart, we need to deal with that elegantly

Tracker for Xenial work

- [ ] nubisproject/nubis-builder#230
- [ ] nubisproject/nubis-base#440
- [ ] nubisproject/ci
- [ ] nubisproject/consul
- [ ] nubisproject/fluent-collector
- [ ] nubisproject/prometheus
- [ ] nubisproject/prometheus-aggregator
- [ ] nubisproject/skel
- [ ] nubisproject/dpaste
